// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mandiroute-buyer-flow/BuyerFlow.tsx": () => import("../components/mockups/mandiroute-buyer-flow/BuyerFlow.tsx")
};
