from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Float, DateTime, Enum, Date
from sqlalchemy.orm import relationship
import enum
import datetime
from database import Base

# --- ENUMS for predefined choices ---

class UserRole(enum.Enum):
    FPO = "fpo"       # Farmer Producer Organization (Seller)
    BUYER = "buyer"   # Supermarket, Cloud Kitchen, etc.
    DRIVER = "driver" # Logistics provider

class ContractStatus(enum.Enum):
    DRAFT = "draft"
    SIGNED = "signed"
    IN_TRANSIT = "in_transit"
    DELIVERED = "delivered"
    PAID = "paid"

# --- DATABASE MODELS ---

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    role = Column(Enum(UserRole))
    phone = Column(String, unique=True, index=True)
    
    # Coordinates for Module 3: Google Maps Spatial Matchmaking
    location_lat = Column(Float, nullable=True) 
    location_lng = Column(Float, nullable=True)

    # Relationships: An FPO can have many crop batches listed
    crop_batches = relationship("CropBatch", back_populates="owner")


class CropBatch(Base):
    __tablename__ = "crop_batches"
    # Related to Module 1: BioTrace Crop Intelligence

    id = Column(Integer, primary_key=True, index=True)
    fpo_id = Column(Integer, ForeignKey("users.id"))
    
    crop_name = Column(String, index=True) # e.g., "Tomato", "Onion"
    quantity_kg = Column(Float)
    quality_grade = Column(String)         # e.g., "Grade A+" (From BioTrace mock)
    base_price_per_kg = Column(Float)
    is_certified = Column(Boolean, default=False)
    
    # Relationships
    owner = relationship("User", back_populates="crop_batches")
    contracts = relationship("Contract", back_populates="batch")


class MarketPrice(Base):
    __tablename__ = "market_prices"
    # Related to Module 2: KhetiNex Price-Arbitrage Engine

    id = Column(Integer, primary_key=True, index=True)
    crop_name = Column(String, index=True)
    market_city = Column(String, index=True) # e.g., "Mumbai", "Delhi"
    price_per_kg = Column(Float)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow)


class Contract(Base):
    __tablename__ = "contracts"
    # Related to Module 4: GenAI Smart Contract & Escrow

    id = Column(Integer, primary_key=True, index=True)
    buyer_id = Column(Integer, ForeignKey("users.id"))
    seller_id = Column(Integer, ForeignKey("users.id"))
    batch_id = Column(Integer, ForeignKey("crop_batches.id"))
    
    total_amount = Column(Float)
    
    # The actual legal text generated by Gemini AI
    contract_text = Column(String) 
    
    status = Column(Enum(ContractStatus), default=ContractStatus.DRAFT)
    
    # Simulates the escrow geofenced payment trigger
    escrow_released = Column(Boolean, default=False) 
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    batch = relationship("CropBatch", back_populates="contracts")

class BioChainVerification(Base):
    __tablename__ = 'biochain_verifications'
    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(String, index=True)
    crop_name = Column(String)
    trust_score = Column(Integer)
    is_verified = Column(Boolean)
    field_score = Column(Float)
    ndvi_score = Column(Float)
    ai_score = Column(Float)
    sensor_score = Column(Float)
    trace_score = Column(Float)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class Farmer(Base):
    __tablename__ = "farmers"
    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(String, unique=True, index=True)
    name = Column(String)
    land_size_acres = Column(Float)
    cluster = Column(String)
    
    harvests = relationship("HarvestRecord", back_populates="farmer")

class HarvestRecord(Base):
    __tablename__ = "harvest_records"
    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(String, ForeignKey("farmers.farmer_id"))
    crop_name = Column(String)
    crop_family = Column(String)
    season = Column(String)
    yield_per_acre = Column(Float)
    quality_grade = Column(String)
    trust_score = Column(Float)
    net_profit_margin = Column(Float)
    harvest_date = Column(Date)
    
    farmer = relationship("Farmer", back_populates="harvests")

class DisputeRecord(Base):
    __tablename__ = "dispute_records"
    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(String, ForeignKey("farmers.farmer_id"))
    business_name = Column(String)
    reason = Column(String)
    proof_url = Column(String)
    penalty_applied = Column(Boolean, default=True)
    points_deducted = Column(Integer, default=30)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    
    farmer = relationship("Farmer")

class SubscriptionTier(enum.Enum):
    FREE = "free"
    PRO = "pro"
    ENTERPRISE = "enterprise"

class BusinessSubscription(Base):
    __tablename__ = "business_subscriptions"
    id = Column(Integer, primary_key=True, index=True)
    business_name = Column(String, unique=True, index=True)
    tier = Column(Enum(SubscriptionTier), default=SubscriptionTier.FREE)
    is_active = Column(Boolean, default=True)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
